package gui_giaodich;

import java.util.ArrayList;
import java.util.List;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import database.Database;
import entities.ChiTietPhieuThue;
import entities.ChiTietThanhToan;
import entities.Dia;
import entities.KhachHang;
import entities.PhiTreHan;
import entities.PhieuThue;
import entities.PhieuTra;
import entities.TaiKhoan;
import entities.ThanhToan;
import entities.TieuDe;
import service.QuanLyCT_PhieuThue;
import service.QuanLyCT_ThanhToan;
import service.QuanLyDia;
import service.QuanLyKhachHang;
import service.QuanLyPhiTreHan;
import service.QuanLyPhieuThue;
import service.QuanLyPhieuTra;
import service.QuanLyTaiKhoan;
import service.QuanLyThanhToan;
import service.QuanLyTieuDe;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class ChiTietThanhToanDialog extends javax.swing.JDialog {

	/**
	 * Creates new form NewJDialog
	 */
	public ChiTietThanhToanDialog(java.awt.Frame parent, boolean modal, String maTT) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlkh = new QuanLyKhachHang();
//		qlpt = new QuanLyPhieuThue();
		qltk = new QuanLyTaiKhoan();
//		ql_ctpt = new QuanLyCT_PhieuThue();
		qltd = new QuanLyTieuDe();
		qldia = new QuanLyDia();
		qltt = new QuanLyThanhToan();
		qlct_tt = new QuanLyCT_ThanhToan();
		qlpth = new QuanLyPhiTreHan();

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtMaPT = new javax.swing.JTextField();
		txtKhachHang = new javax.swing.JTextField();
		txtNguoiLap = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txtNgayLap = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel5 = new javax.swing.JLabel();
		txtTongTien = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setTitle("Chi tiết phiếu thuê");
		setResizable(false);

		jLabel1.setText("Mã TT:");

		jLabel2.setText("Khách hàng:");

		txtMaPT.setEditable(false);

		txtKhachHang.setEditable(false);

		txtNguoiLap.setEditable(false);

		jLabel3.setText("Ngày lập:");

		jLabel4.setText("Người lập:");

		txtNgayLap.setEditable(false);

		jPanel2.setLayout(new java.awt.BorderLayout());

		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTable1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
		jTable1.setRowHeight(22);
		jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Tên đĩa", "Phí nợ", "Số tiền thanh toán" }) {
			boolean[] canEdit = new boolean[] { false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});

		jScrollPane1.setViewportView(jTable1);
		jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		jLabel5.setText("Chi tiết thanh toán:");

		txtTongTien.setEditable(false);

		jLabel6.setText("Tổng tiền:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(21, 21, 21).addComponent(txtTongTien,
														javax.swing.GroupLayout.PREFERRED_SIZE, 328,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(10, 10, 10).addComponent(txtMaPT,
														javax.swing.GroupLayout.PREFERRED_SIZE, 328,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(21, 21, 21).addComponent(txtKhachHang,
														javax.swing.GroupLayout.PREFERRED_SIZE, 328,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85,
										Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(10, 10, 10).addComponent(txtNgayLap,
														javax.swing.GroupLayout.PREFERRED_SIZE, 328,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(21, 21, 21).addComponent(txtNguoiLap,
														javax.swing.GroupLayout.PREFERRED_SIZE, 328,
														javax.swing.GroupLayout.PREFERRED_SIZE)))))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(11, 11, 11)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(txtMaPT, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2).addComponent(txtKhachHang,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3)
								.addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel4).addComponent(txtNguoiLap,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
				.addGap(18, 18, 18).addComponent(jLabel5).addGap(15, 15, 15)
				.addComponent(
						jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel6)
						.addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void setData(String maTT){
    	ThanhToan tt = qltt.chiTietThanhToan(maTT);    	
    	TaiKhoan tk = qltk.chiTietTaiKhoan(tt.getTaiKhoan().getTenTK());
    	KhachHang kh = qlkh.chiTietKhachHang(tt.getKhachHang().getMaKH());
    	txtMaPT.setText(tt.getMaTT());
    	txtNgayLap.setText(tt.getNgayThanhToan());
    	txtKhachHang.setText(kh.getTenKH());
    	txtNguoiLap.setText(tk.getHoTen());
    	txtTongTien.setText(tt.getTongTien()+"");
    	DocDuLieuDatabaseVaoTable(maTT);
    }

	public void DocDuLieuDatabaseVaoTable(String maTT) {
		List<ChiTietThanhToan> list = new ArrayList<ChiTietThanhToan>();
		qlct_tt = new QuanLyCT_ThanhToan();
		list = qlct_tt.getcttt_TheoMATT(maTT);
		DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
		for (ChiTietThanhToan cttt : list) {
			PhiTreHan pth = qlpth.chiTietPhiTreHan(cttt.getPhiTreHan().getPhieuTra().getMaPTr());
			PhieuTra ptra = qlptr.chiTietPhieuTra(pth.getPhieuTra().getMaPTr());
			Dia d = qldia.chiTietDia(ptra.getDia().getMaDia());
			TieuDe td = qltd.chiTietTieuDe(d.getTieuDe().getMaTD());
			dm.addRow(new Object[] { td.getTenTD(), pth.getTongTien(), cttt.getSoTien()});
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ChiTietThanhToanDialog.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ChiTietThanhToanDialog.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ChiTietThanhToanDialog.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ChiTietThanhToanDialog.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ChiTietThanhToanDialog dialog = new ChiTietThanhToanDialog(new javax.swing.JFrame(), true, maPT);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField txtKhachHang;
	private javax.swing.JTextField txtNguoiLap;
	private javax.swing.JTextField txtTongTien;
	private javax.swing.JTextField txtMaPT;
	private javax.swing.JTextField txtNgayLap;

	private static String maPT;

	private QuanLyKhachHang qlkh;
//	private QuanLyPhieuThue qlpt;
	private QuanLyTaiKhoan qltk;
//	private QuanLyCT_PhieuThue ql_ctpt;
	private QuanLyTieuDe qltd;
	private QuanLyDia qldia;
	private QuanLyThanhToan qltt;
	private QuanLyCT_ThanhToan qlct_tt;
	private QuanLyPhiTreHan qlpth;
	private QuanLyPhieuTra qlptr;
	// End of variables declaration//GEN-END:variables
}
