/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_giaodich;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import entities.TaiKhoan;
import gui_heThong.DatHang_DS_Gui;

/**
 *
 * @author nmrhu
 */
public class DatHang_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form TraCuu_Gui
	 */
	public DatHang_Gui() {
		initComponents();
        khoiTao();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new java.awt.Dimension(1300, 650));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setPreferredSize(new java.awt.Dimension(1274, 605));
		jPanel2.setLayout(new java.awt.BorderLayout());

		jLabel2.setForeground(new java.awt.Color(102, 102, 102));
		jLabel2.setText("/ Đặt hàng");

		jLabel1.setForeground(new java.awt.Color(51, 153, 255));
		jLabel1.setText("  Giao dịch");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addContainerGap()
				.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE).addContainerGap()));
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	public static void khoiTao() {
		ds_DatHang_pn = new DatHang_DS_Gui();
		lapDatHang_pn = new DatHang_Lap_Gui();
		
		jPanel2.add(ds_DatHang_pn);
//		ds_DatHang_pn.phanQuyen(tk);
		ds_DatHang_pn.setVisible(true);
	}

	public static void dsDatHang() {
		ds_DatHang_pn.phanQuyen(tk);
		lapDatHang_pn.setVisible(false);

		jPanel2.add(ds_DatHang_pn);
		ds_DatHang_pn.setVisible(true);

	}

	public static void lapDatHang() {
		lapDatHang_pn.setData(tk);
		ds_DatHang_pn.setVisible(false);

		jPanel2.add(lapDatHang_pn);
		lapDatHang_pn.setVisible(true);
	}

	public static void setData(TaiKhoan tk_sql) {
		tk = tk_sql;
		ds_DatHang_pn.phanQuyen(tk);
	}
	
//    public static DatHang_DS_Gui ds_DatHang_pn;
	public static gui_heThong.DatHang_DS_Gui ds_DatHang_pn;
	public static DatHang_Lap_Gui lapDatHang_pn;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private static javax.swing.JPanel jPanel2;

	public static TaiKhoan tk;
	// End of variables declaration//GEN-END:variables
}
