package gui_danhMuc;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.ListModel;

import database.Database;
import entities.Dia;
import entities.KhachHang;
import entities.TaiKhoan;
import entities.TheLoai;
import entities.TieuDe;
import gui_main.Main_Gui;
import service.QuanLyDia;
import service.QuanLyTieuDe;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class Dia_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public Dia_Dialog(java.awt.Frame parent, boolean modal) {
    	super(parent, modal);
        initComponents();
        
        getID();
        
        jPopupMenu1.add(jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	Database.getInstance().connect();
		qltd = new QuanLyTieuDe();
		qldia = new QuanLyDia();

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaDia = new javax.swing.JTextField();
        txtMaDia.setEditable(false);
        radPhim = new javax.swing.JRadioButton();
        radGame = new javax.swing.JRadioButton();
        btnLuu = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        txtTieuDe = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DefaultListModel<TieuDe> model_list = new DefaultListModel<TieuDe>();
		jList1.setModel(model_list);
		jList1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {
				int row = jList1.getSelectedIndex();
				ListModel<TieuDe> model = jList1.getModel();
				td = model.getElementAt(row);
				txtTieuDe.setText(td.getTenTD());
				jPopupMenu1.setVisible(false);
			}
		});
		jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPopupMenu1.setFocusable(false);

		setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Mã đĩa:");

        jLabel6.setText("Tên đĩa:");

        jLabel7.setText("Thể loại:");

        
        radPhim.setSelected(true);
        radPhim.setText("Phim");
        radPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRad(radPhim);
            }
        });

        radGame.setText("Game");
        radGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRad(radGame);
            }
        });

        btnLuu.setBackground(new java.awt.Color(0, 153, 255));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\save_30px.png")); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(td == null)
                	JOptionPane.showMessageDialog(null, "Vui lÃ²ng chá»�n tiÃªu Ä‘á»�");
                else {
                	Dia d = getDia();
                	main.dia_pn.ThemDia(d);
        	    	dispose();
                }
            }
        });

        btnDong.setBackground(new java.awt.Color(255, 0, 0));
        btnDong.setForeground(new java.awt.Color(255, 255, 255));
        btnDong.setIcon(new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\delete_30px.png")); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	main.dia_pn.DocDuLieuDatabaseVaoTable("");
        		dispose();
            }
        });

        txtTieuDe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTieuDeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaDia, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radPhim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radGame))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtTieuDe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtMaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(radPhim)
                    .addComponent(radGame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnDong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    //SÆ° kiá»‡n txtTieuDe
    private void txtTieuDeKeyReleased(java.awt.event.KeyEvent evt) {
    	String tieuDe = txtTieuDe.getText().trim();
        if(tieuDe.equals("")){
        	DocDuLieuDatabaseVaoTable("");
            jPopupMenu1.show(txtTieuDe, 0, txtTieuDe.getHeight());
        }else {
        	DocDuLieuDatabaseVaoTable(tieuDe);
        	jPopupMenu1.show(txtTieuDe, 0, txtTieuDe.getHeight());
        }
    }

    public void getID() {
		int id = qldia.getMaDia();
		String maTD = null;
		if (id == 0) {
			maTD = "BD00001";
		} else if (id < 10)
			maTD = "BD0000" + id;
		else if (id < 100)
			maTD = "BD000" + id;
		else if (id < 1000)
			maTD = "BD00" + id;
		else if (id < 10000)
			maTD = "BD0" + id;
		else
			maTD = "BD" + id;

		txtMaDia.setText(maTD);
	}
    
    public void getRad(JRadioButton rad) {
    	radGame.setSelected(false);
		radPhim.setSelected(false);
		rad.setSelected(true);
    }
    
    public Dia getDia() {
    	int theLoai;
    	if (radPhim.isSelected())
			theLoai = 1;
		else
			theLoai = 2;
		Dia dia = new Dia(new TheLoai(theLoai), td);
		return dia;
	}
    
    public void XoaHetDuLieuTrenTableModel() {
		DefaultListModel<TieuDe> dm = (DefaultListModel<TieuDe>) jList1.getModel();
		dm.clear();
	}

	public void DocDuLieuDatabaseVaoTable(String txtTim) {
		XoaHetDuLieuTrenTableModel();
		List<TieuDe> list = new ArrayList<TieuDe>();
		qltd = new QuanLyTieuDe();
		if(txtTim.equals(""))
			list = qltd.danhSachTieuDe();
		else
			list = qltd.tim_TieuDe(txtTim);
		
		if(!list.isEmpty()) {
			DefaultListModel<TieuDe> dm = (DefaultListModel<TieuDe>) jList1.getModel();
			for (TieuDe tieuDe : list) {
				dm.addElement(tieuDe);
			}
		}else {
			XoaHetDuLieuTrenTableModel();
		}		
	}
	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dia_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dia_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dia_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dia_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dia_Dialog dialog = new Dia_Dialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<TieuDe> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radGame;
    private javax.swing.JRadioButton radPhim;
    private javax.swing.JTextField txtMaDia;
    private javax.swing.JTextField txtTieuDe;
    
    private TieuDe td;
    private QuanLyTieuDe qltd;
    private QuanLyDia qldia;
    private Main_Gui main;
    // End of variables declaration//GEN-END:variables
}
