/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_danhMuc;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import entities.KhachHang;
import entities.TaiKhoan;
import gui_main.Main_Gui;
import service.QuanLyKhachHang;
import service.QuanLyTaiKhoan;

/**
 *
 * @author nmrhu
 */
public class KhachHang_Dialog extends javax.swing.JDialog {

	/**
	 * Creates new form TaiKhoan_DL
	 */
	public KhachHang_Dialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		getID();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		btnLuu = new javax.swing.JButton();
		btnXoaTrang = new javax.swing.JButton();
		txtMaKH = new javax.swing.JTextField();
		txtMaKH.setEditable(false);
		txtHoTen = new javax.swing.JTextField();
		txtSDT = new javax.swing.JTextField();
		txtDiaChi = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setResizable(false);
		setBackground(new java.awt.Color(255, 255, 255));
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		btnLuu.setBackground(new java.awt.Color(0, 153, 255));
		btnLuu.setForeground(new java.awt.Color(255, 255, 255));
		btnLuu.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\save_30px.png")); // NOI18N
		btnLuu.setText("Lưu");
		btnLuu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (quyen == 1)
					Them();
				if (quyen == 2)
					CapNhat();
			}
		});

		txtSDT.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (Character.isLetter(c) && !e.isAltDown()) {
					e.consume();
				}
			}
		});
		
		btnXoaTrang.setBackground(new java.awt.Color(255, 0, 0));
		btnXoaTrang.setForeground(new java.awt.Color(255, 255, 255));
		btnXoaTrang.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\delete_30px.png")); // NOI18N
		btnXoaTrang.setText("Đóng");
		btnXoaTrang.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
//				main.khachHang_pn.DocDuLieuDatabaseVaoTable("");
				dispose();
			}
		});

		jLabel1.setText("MãKH:");

		jLabel2.setText("Họ tên:");

		jLabel3.setText("SĐT:");

		jLabel4.setText("Địa chỉ:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtMaKH).addComponent(txtHoTen).addComponent(txtSDT)
								.addComponent(txtDiaChi)
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 153,
												Short.MAX_VALUE)))
						.addGap(23, 23, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1).addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3).addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnLuu).addComponent(btnXoaTrang))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public void getID() {
		int id = qlkh.getMaKH();
		String maKH = "";
		if (id == 0) {
			maKH = "KH00001";
		} else if (id < 10)
			maKH = "KH0000" + id;
		else if (id < 100)
			maKH = "KH000" + id;
		else if (id < 1000)
			maKH = "KH00" + id;
		else if (id < 10000)
			maKH = "KH0" + id;
		else
			maKH = "KH" + id;

		txtMaKH.setText(maKH);
	}

	public void setData(KhachHang kh) {
		txtMaKH.setText(kh.getMaKH());
		txtHoTen.setText(kh.getTenKH());
		txtSDT.setText(kh.getSdt());
		txtDiaChi.setText(kh.getDiaChi());
	}

	public void lienLacKhachHang(KhachHang kh) {
		txtMaKH.setText(kh.getMaKH());
		txtHoTen.setText(kh.getTenKH());
		txtSDT.setText(kh.getSdt());
		txtDiaChi.setText(kh.getDiaChi());
		txtHoTen.setEditable(false);
		txtSDT.setEditable(false);
		txtDiaChi.setEditable(false);
		btnLuu.setEnabled(false);
	}

	public void Them() {
		if (kiemTraNhap()) {
			KhachHang kh = getKhachHang();
			main.khachHang_pn.ThemKhachHang(kh);
			main.phieuThue_pn.LapPhieu_pn.DocDuLieuDatabaseVaoList("");
			main.datHang_pn.lapDatHang_pn.DocDuLieuDatabaseVaoList("");
//			main.datHang_pn.lapDatHang();
			JOptionPane.showMessageDialog(null, "Thêm thành công");
			dispose();
		}
	}

	public void CapNhat() {
		if (kiemTraNhap()) {
			KhachHang kh = getKhachHang();
			main.khachHang_pn.CapNhatKhachHang(kh);
			dispose();
		}
	}

	public boolean kiemTraNhap() {
		String hoTen = txtHoTen.getText();
		String diaChi = txtDiaChi.getText();
		String sdt = txtSDT.getText();

		if (hoTen.equals("") || diaChi.equals("") || sdt.equals("")) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
			return false;
		}
		if (sdt.length() != 10) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại hợp lệ với 10 số");
			txtSDT.requestFocus();
			return false;
		}
		return true;
	}

	public KhachHang getKhachHang() {
		String maKH = txtMaKH.getText();
		String hoTen = txtHoTen.getText();
		String sdt = txtSDT.getText();
		String diaChi = txtDiaChi.getText();
		KhachHang kh = new KhachHang(maKH, hoTen, sdt, diaChi);
		return kh;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(KhachHang_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(KhachHang_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(KhachHang_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(KhachHang_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				KhachHang_Dialog dialog = new KhachHang_Dialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLuu;
	private javax.swing.JButton btnXoaTrang;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField txtDiaChi;
	private javax.swing.JTextField txtHoTen;
	private javax.swing.JTextField txtMaKH;
	private javax.swing.JTextField txtSDT;

	private Main_Gui main;
	public static int quyen;
	private QuanLyKhachHang qlkh = new QuanLyKhachHang();

	// End of variables declaration//GEN-END:variables
}
