package gui_danhMuc;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import database.Database;
import entities.ChiTietPhieuDat;
import entities.Dia;
import entities.KhachHang;
import entities.PhieuDat;
import entities.TaiKhoan;
import gui_giaodich.PhieuThue_Dialog;
import gui_giaodich.ThanhToan_Dialog;
import gui_main.Main_Gui;
import service.QuanLyKhachHang;
import service.QuanLyTaiKhoan;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class KhachHang_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form TaiKhoan
	 */
	public KhachHang_Gui() {
		initComponents();
		DocDuLieuDatabaseVaoTable("");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlkh = new QuanLyKhachHang();

		jPopupMenu1 = new javax.swing.JPopupMenu();
		jPopupMenu1.setFocusable(false);

		mnThanhToan = new javax.swing.JMenuItem();
		mnThanhToan.setText("Thanh toán phí trễ hạn");
		mnThanhToan.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				gui_heThong.ThanhToan_Dialog dialog = new gui_heThong.ThanhToan_Dialog(main, true,1);
//				ThanhToan_Dialog dialog = new ThanhToan_Dialog(main, true);
				dialog.setTitle("Thanh toán phí trễ hạn");
				dialog.setLocationRelativeTo(main);
				dialog.setData(kh);
				dialog.setTaiKhoan(tk);
				dialog.setVisible(true);
			}
		});
		jPopupMenu1.add(mnThanhToan);

		mnXemLichSu = new javax.swing.JMenuItem();
		mnXemLichSu.setText("Lịch sử giao dịch");
		mnXemLichSu.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				LichSuThue_Dialog dialog = new LichSuThue_Dialog(main, true);
				dialog.setTitle("Lịch sử giao dịch");
				dialog.setLocationRelativeTo(main);
				dialog.setData(kh);
				dialog.setVisible(true);
			}
		});
		jPopupMenu1.add(mnXemLichSu);

		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableKhachHang = new javax.swing.JTable();
		btnThem1 = new javax.swing.JButton();
		btnCapNhat = new javax.swing.JButton();
		btnTim = new javax.swing.JButton();
		btnXoa = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new java.awt.Dimension(1300, 650));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));
		jPanel2.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		jTableKhachHang.setRowHeight(22);
		jTableKhachHang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTableKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
		jTableKhachHang.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã khách hàng", "Họ tên", "SDT", "Địa chỉ" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableKhachHang.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (SwingUtilities.isRightMouseButton(e)) {
					jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
				} else {
					ChiTietKhachHang();
				}
			}
		});
		jScrollPane1.setViewportView(jTableKhachHang);
		jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		btnThem1.setBackground(new java.awt.Color(0, 153, 255));
		btnThem1.setForeground(new java.awt.Color(255, 255, 255));
		btnThem1.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\add_30px.png")); // NOI18N
		btnThem1.setText("Thêm mới");
		btnThem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				KhachHang_Dialog dialog = new KhachHang_Dialog(main, true);
				dialog.setTitle("Thêm khách hàng");
				dialog.setLocationRelativeTo(main);
				dialog.quyen = 1;
				dialog.setVisible(true);
				
			}
		});

		btnCapNhat.setBackground(new java.awt.Color(255, 204, 51));
		btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
		btnCapNhat.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\edit_30px.png")); // NOI18N
		btnCapNhat.setText("Cập nhật");
		btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (kh == null) {
					JOptionPane.showMessageDialog(null, "Chọn khách hàng cần cập nhât");
				} else {
					KhachHang_Dialog dialog = new KhachHang_Dialog(main, true);
					dialog.setTitle("Cập nhật khách hàng");
					dialog.setData(kh);
					dialog.setLocationRelativeTo(main);
					dialog.quyen = 2;
					dialog.setVisible(true);
					kh = null;
				}
			}
		});

		btnTim.setBackground(new java.awt.Color(0, 153, 255));
		btnTim.setForeground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\search_30px.png")); // NOI18N
		btnTim.setText("Tìm kiếm");
		btnTim.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String tim = txtTim.getText().toString();
				if (tim.equals(""))
					DocDuLieuDatabaseVaoTable("");
				else
					DocDuLieuDatabaseVaoTable(tim);
			}
		});

		btnXoa.setBackground(new java.awt.Color(255, 51, 51));
		btnXoa.setForeground(new java.awt.Color(255, 255, 255));
		btnXoa.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\delete_30px.png")); // NOI18N
		btnXoa.setText("Xóa");
		btnXoa.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				if (kh == null) {
					JOptionPane.showMessageDialog(null, "Chọn khách hàng cần xóa");
				} else {
					XoaKhachHang(kh);
					kh = null;
				}
			}
		});

		jLabel2.setForeground(new java.awt.Color(102, 102, 102));
		jLabel2.setText("/ Khách hàng");

		jLabel1.setForeground(new java.awt.Color(51, 153, 255));
		jLabel1.setText("   Danh mục");

		txtTim = new JTextField();
		txtTim.setColumns(10);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(20).addComponent(jPanel2, GroupLayout.PREFERRED_SIZE,
						1260, GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup().addGap(10).addGroup(layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(10)
								.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
								.addGap(270)
								.addComponent(btnThem1, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
								.addGap(10)
								.addComponent(btnCapNhat, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
								.addGap(10)
								.addComponent(btnXoa, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
								.addGap(0)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)))));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(10)
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 60,
										GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThem1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
								.addComponent(btnCapNhat).addComponent(btnXoa)
								.addGroup(layout.createSequentialGroup().addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)))
						.addGap(50)
						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)));
		this.setLayout(layout);
	}

	public void XoaHetDuLieuTrenTableModel() {
		DefaultTableModel dm = (DefaultTableModel) jTableKhachHang.getModel();
		dm.getDataVector().removeAllElements();
	}

	public void DocDuLieuDatabaseVaoTable(String txt) {
		XoaHetDuLieuTrenTableModel();
		List<KhachHang> list = new ArrayList<KhachHang>();
		qlkh = new QuanLyKhachHang();

		if (txt.equals(""))
			list = qlkh.dsKhachHang();
		else
			list = qlkh.tim_KhachHang(txt);

		if (list.size() == 0) {
			JOptionPane.showMessageDialog(null, "Không tìm thấy");
			list = qlkh.dsKhachHang();
		}

		DefaultTableModel dm = (DefaultTableModel) jTableKhachHang.getModel();
		for (KhachHang kh : list) {
			dm.addRow(new Object[] { kh.getMaKH(), kh.getTenKH(), kh.getSdt(), kh.getDiaChi() });
		}
	}

	public void ChiTietKhachHang() {
		int row = jTableKhachHang.getSelectedRow();
		TableModel model = jTableKhachHang.getModel();
		String maKH = model.getValueAt(row, 0).toString();
		kh = qlkh.chiTietKhachHang(maKH);
	}

	public void ThemKhachHang(KhachHang kh) {
		qlkh.themKhachHang(kh);
		DocDuLieuDatabaseVaoTable("");
	}

	public void CapNhatKhachHang(KhachHang kh) {
		try {
			qlkh.capNhatKhachHang(kh);
			JOptionPane.showMessageDialog(null, "Cập nhật thành công");
			DocDuLieuDatabaseVaoTable("");
		} catch (Exception e) {
			// TODO: handle exception
			JOptionPane.showMessageDialog(null, "Cập nhật không thành công");
		}
	}

	public void XoaKhachHang(KhachHang kh) {
		int hoi = JOptionPane.showConfirmDialog(this,
				"Bạn có chắc chắn xóa " + kh.getMaKH() + " - " + kh.getTenKH() + " không ?", "Chú ý",
				JOptionPane.YES_NO_OPTION);
		if (hoi == JOptionPane.YES_OPTION) {
			DefaultTableModel dm = (DefaultTableModel) jTableKhachHang.getModel();
			if (jTableKhachHang.getRowCount() == 1)
				dm.removeRow(0);
			try {
				qlkh.delete(kh.getMaKH());
				DocDuLieuDatabaseVaoTable("");
				JOptionPane.showMessageDialog(null, "Xóa thành công ");
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(null, "Khách hàng không thể xóa");
			}
		}
	}
	
	public static void phanQuyen(TaiKhoan tk_sql) {
		tk = tk_sql;
		if(tk.getQuyen() == 1) {
			btnXoa.setEnabled(false);
		}else {
			btnXoa.setEnabled(true);
		}		
	}

	private javax.swing.JPopupMenu jPopupMenu1;
	private javax.swing.JMenuItem mnThanhToan;
	private javax.swing.JMenuItem mnXemLichSu;
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnCapNhat;
	private javax.swing.JButton btnThem1;
	public static javax.swing.JButton btnXoa;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableKhachHang;

	private QuanLyKhachHang qlkh;
	private KhachHang kh;
	private Main_Gui main;
	private JButton btnTim;
	private JTextField txtTim;
	
	private static TaiKhoan tk;

	// End of variables declaration//GEN-END:variables
}
