/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_danhMuc;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import database.Database;
import entities.PhieuThue;
import entities.TaiKhoan;
import entities.ThanhToan;
import gui_giaodich.ChiTietPhieuThueDialog;
import gui_giaodich.ChiTietThanhToanDialog;
import gui_main.Main_Gui;
import service.QuanLyPhieuThue;
import service.QuanLyTaiKhoan;
import service.QuanLyThanhToan;

/**
 *
 * @author nmrhu
 */
public class ThanhToan_Panel extends javax.swing.JPanel {

    /**
     * Creates new form ThanhToan_Panel
     */
    public ThanhToan_Panel(String maKH_) {
        initComponents();
        maKH = maKH_;
        
        DocDuLieuDatabaseVaoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	Database.getInstance().connect();
		qltt = new QuanLyThanhToan();
		qltk = new QuanLyTaiKhoan();
		
		jPopupMenu1 = new javax.swing.JPopupMenu();
		jPopupMenu1.setFocusable(false);
    	
		mnCTPT = new javax.swing.JMenuItem();
		mnCTPT.setText("Chi tiết thanh toán");
		mnCTPT.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				ChiTietThanhToanDialog dialog = new ChiTietThanhToanDialog(main, true, maTT);
				dialog.setTitle("Chi tiết thanh toán");
				dialog.setLocationRelativeTo(main);
				dialog.setData(maTT);
				dialog.setVisible(true);
			}
		});
		jPopupMenu1.add(mnCTPT);

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setRowHeight(22);
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
		}, new String[] { "MaTT", "Ngày thanh toán", "Số tiền","Người lập" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		
		jTable1.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if(SwingUtilities.isRightMouseButton(e)) {
					jPopupMenu1.show(e.getComponent(), e.getX(), e.getY());
				}else {
					int row = jTable1.getSelectedRow();
					TableModel model = jTable1.getModel();
					maTT = model.getValueAt(row, 0).toString();
				}
			}
		});
		
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }

    public void DocDuLieuDatabaseVaoTable() {
		List<ThanhToan> list = new ArrayList<ThanhToan>();
		qltt = new QuanLyThanhToan();
		list = qltt.tim_ThanhToan_KhachHang(maKH);
		DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
		for (ThanhToan tt : list) {
			TaiKhoan tk = qltk.chiTietTaiKhoan(tt.getTaiKhoan().getTenTK());
			dm.addRow(new Object[] {tt.getMaTT(),tt.getNgayThanhToan(),tt.getTongTien(),tk.getHoTen()});
		}
	}
    
    private javax.swing.JPopupMenu jPopupMenu1;
	private javax.swing.JMenuItem mnCTPT;
    
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    
    private QuanLyThanhToan qltt;
    private QuanLyTaiKhoan qltk;
    
    private String maKH;
    private String maTT;
    
    private Main_Gui main;
}
