/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_heThong;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import database.Database;
import entities.ChiTietPhieuThue;
import entities.Dia;
import entities.KhachHang;
import entities.PhieuThue;
import entities.PhieuTra;
import entities.TaiKhoan;
import entities.TieuDe;
import gui_giaodich.GhiNhanTra_Gui;
import gui_giaodich.PhieuTra_Gui;
import service.QuanLyCT_PhieuThue;
import service.QuanLyDia;
import service.QuanLyKhachHang;
import service.QuanLyPhieuThue;
import service.QuanLyPhieuTra;
import service.QuanLyTaiKhoan;
import service.QuanLyTieuDe;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author nmrhu
 */
public class PhieuTra_DS_Gui extends javax.swing.JPanel {

	/**
	 * Creates new form TraCuu_KhachHang_Gui
	 */
	public PhieuTra_DS_Gui() {
		initComponents();

		DocDuLieuDatabaseVaoTable("",0);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qlptr = new QuanLyPhieuTra();
		qlpt = new QuanLyPhieuThue();
		qltd = new QuanLyTieuDe();
		qldia = new QuanLyDia();
		ql_ctpt = new QuanLyCT_PhieuThue();
		qltk = new QuanLyTaiKhoan();

		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableDia = new javax.swing.JTable();
		btnTim = new javax.swing.JButton();
		txtTim = new javax.swing.JTextField();
		btnTim1 = new javax.swing.JButton();
		btnLapPhieuThue = new javax.swing.JButton();

		setBackground(new java.awt.Color(255, 255, 255));
		setPreferredSize(new java.awt.Dimension(1274, 605));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

		jTableDia.setRowHeight(22);
		jTableDia.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Mã PTr", "Mã đĩa", "Tên đĩa", "Hạn Trả", "Ngày Trả", "Quá hạn", "Hư hỏng", "Người lập" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTableDia.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jTableDia.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
		jScrollPane1.setViewportView(jTableDia);

		jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		btnTim.setBackground(new java.awt.Color(0, 153, 255));
		btnTim.setForeground(new java.awt.Color(255, 255, 255));
		btnTim.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\search_30px.png")); // NOI18N
		btnTim.setText("Tìm kiếm");
		btnTim.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				String txt = txtTim.getText().toString();
				DocDuLieuDatabaseVaoTable(txt, 0);
			}
		});

		btnTim1.setBackground(new java.awt.Color(0, 153, 255));
		btnTim1.setForeground(new java.awt.Color(255, 255, 255));
		btnTim1.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\DoAnQuanLyChoThueBangDia\\XayDungPhanMem\\img\\filter_30px.png")); // NOI18N
		btnTim1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DocDuLieuDatabaseVaoTable("", 1);
				txtTim.setText("");
			}
		});

		btnLapPhieuThue.setBackground(new java.awt.Color(51, 153, 255));
		btnLapPhieuThue.setForeground(new java.awt.Color(255, 255, 255));
		btnLapPhieuThue.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\add_property_30px.png")); // NOI18N
		btnLapPhieuThue.setText("Ghi nhận trả");
		btnLapPhieuThue.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pt.lapPhieuTra(tk);
			}
		});

		dateChooser = new JDateChooser();
		dateChooser.setDate(new Date());

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGap(50)
				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 1170, GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
								.addComponent(txtTim, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(btnTim, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
								.addGap(18)
								.addComponent(dateChooser, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(btnTim1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(btnLapPhieuThue, GroupLayout.PREFERRED_SIZE, 201,
										GroupLayout.PREFERRED_SIZE)))
				.addContainerGap(54, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGap(32)
				.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(dateChooser, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(Alignment.LEADING, layout.createParallelGroup(Alignment.TRAILING, false)
								.addComponent(btnLapPhieuThue, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(Alignment.LEADING,
										layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(txtTim, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(btnTim, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
								.addComponent(btnTim1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
				.addPreferredGap(ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
				.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 450, GroupLayout.PREFERRED_SIZE)
				.addContainerGap(52, Short.MAX_VALUE)));
		this.setLayout(layout);
	}

	public void XoaHetDuLieuTrenTableModel() {
		DefaultTableModel dm = (DefaultTableModel) jTableDia.getModel();
		dm.getDataVector().removeAllElements();
	}

	public void DocDuLieuDatabaseVaoTable(String txt, int tim) {
		XoaHetDuLieuTrenTableModel();
		List<PhieuTra> list = new ArrayList<PhieuTra>();
		qlptr = new QuanLyPhieuTra();

		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		if (tim == 1) {
			
			String date = sdf.format(dateChooser.getDate());
			list = qlptr.timPhieuTra_Ngay(date);

			if (list.isEmpty()) {
				JOptionPane.showMessageDialog(null, "Không tìm thấy");
				dateChooser.setDate(new Date());
				String date1 = sdf.format(dateChooser.getDate());
				list = qlptr.timPhieuTra_Ngay(date1);
			}

		} else {
			dateChooser.setDate(new Date());
			String date1 = sdf.format(dateChooser.getDate());
			if (txt.equals(""))
				list = qlptr.timPhieuTra_Ngay(date1);
			else {
				list = qlptr.timPhieuTra_Nhap(txt);
				if (list.isEmpty()) {
					JOptionPane.showMessageDialog(null, "Không tìm thấy");
					list = qlptr.timPhieuTra_Ngay(date1);
				}
			}
		}

		DefaultTableModel dm = (DefaultTableModel) jTableDia.getModel();
		for (PhieuTra ptra : list) {
			Dia d = qldia.chiTietDia(ptra.getDia().getMaDia());
			TieuDe td = qltd.chiTietTieuDe(d.getTieuDe().getMaTD());
			ChiTietPhieuThue ctpt = ql_ctpt.ChiTietPhieuThue_PT_Dia(ptra.getPt().getMaPT(), d.getMaDia());
			TaiKhoan tk = qltk.chiTietTaiKhoan(ptra.getNhanVien().getTenTK());
			String quaHan, huHong;
			if (ptra.getQuaHan() == 1)
				quaHan = "Có";
			else
				quaHan = "Không";

			if (ptra.getHuHong() == 1)
				huHong = "Có";
			else
				huHong = "Không";

			dm.addRow(new Object[] { ptra.getMaPTr(), d.getMaDia(), td.getTenTD(), ctpt.getHanTra(), ptra.getNgayTra(),
					quaHan, huHong, tk.getHoTen() });
		}
	}
	
	public static void setData(TaiKhoan tk_sql) {
    	if(!(tk_sql == null)) {
			tk = tk_sql;
		}
    }
	private PhieuTra_Gui pt;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLapPhieuThue;
	private javax.swing.JButton btnTim;
	private javax.swing.JButton btnTim1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableDia;
	private javax.swing.JTextField txtTim;

	private JDateChooser dateChooser;

	private QuanLyPhieuThue qlpt;
	private QuanLyPhieuTra qlptr;
	private QuanLyDia qldia;
	private QuanLyCT_PhieuThue ql_ctpt;
	private QuanLyTieuDe qltd;
	private QuanLyTaiKhoan qltk;
	
	public static TaiKhoan tk;
}
