/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_heThong;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

import entities.TaiKhoan;
import gui_main.Main_Gui;
import service.QuanLyTaiKhoan;

import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;

/**
 *
 * @author nmrhu
 */
public class TaiKhoan_Dialog extends javax.swing.JDialog {

	/**
	 * Creates new form TaiKhoan_DL
	 */
	public TaiKhoan_Dialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		radKhong = new javax.swing.JRadioButton();
		jLabel5 = new javax.swing.JLabel();
		btnLuu = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		btnXoaTrang = new javax.swing.JButton();
		btnXoaTrang.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				main.taiKhoan_pn.DocDuLieuDatabaseVaoTable();
				dispose();
			}
		});
		jLabel7 = new javax.swing.JLabel();
		txtTenTK = new javax.swing.JTextField();
		txtMatKhau = new javax.swing.JTextField();
		txtHoTen = new javax.swing.JTextField();
		txtEmail = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		txtSDT = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		cbbPhanQuyen = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		radCo = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();

		txtSDT.addKeyListener(new KeyAdapter() {
			@Override
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (Character.isLetter(c) && !e.isAltDown()) {
					e.consume();
				}
			}
		});

//        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		radKhong.setText("Không");
		radKhong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				getRad(radKhong);
			}
		});

		jLabel5.setText("SDT:");

		btnLuu.setBackground(new java.awt.Color(0, 153, 255));
		btnLuu.setForeground(new java.awt.Color(255, 255, 255));
		btnLuu.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\save_30px.png")); // NOI18N
		btnLuu.setText("Lưu");
		btnLuu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				if (quyen == 1)
					Them();
				if (quyen == 2)
					CapNhat();
			}
		});

		jLabel6.setText("Phân quyền:");

		btnXoaTrang.setBackground(new java.awt.Color(255, 0, 0));
		btnXoaTrang.setForeground(new java.awt.Color(255, 255, 255));
		btnXoaTrang.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\delete_30px.png")); // NOI18N
		btnXoaTrang.setText("Đóng");

		jLabel7.setText("Truy cập:");

		jLabel1.setText("Tên tài khoản:");

		jLabel2.setText("Mật khẩu:");

		cbbPhanQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lý" }));

		jLabel3.setText("Họ tên");

		radCo.setSelected(true);
		radCo.setText("Có");
		radCo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				getRad(radCo);
			}
		});

		jLabel4.setText("Email");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(txtTenTK).addComponent(txtMatKhau).addComponent(txtHoTen)
								.addComponent(txtEmail).addComponent(txtSDT)
								.addComponent(cbbPhanQuyen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createSequentialGroup().addComponent(radCo)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(radKhong))
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, 153,
												Short.MAX_VALUE)))
						.addGap(23, 23, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1)
						.addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
						.addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
						.addComponent(cbbPhanQuyen, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel7)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(radCo).addComponent(radKhong)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(btnLuu)
						.addComponent(btnXoaTrang))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void getRad(JRadioButton rad) {
		radCo.setSelected(false);
		radKhong.setSelected(false);
		rad.setSelected(true);
	}

	public void setData(TaiKhoan tk) {
		txtTenTK.setEditable(false);
		txtTenTK.setText(tk.getTenTK());
		txtMatKhau.setText(tk.getMatKhau());
		txtHoTen.setText(tk.getHoTen());
		txtSDT.setText(tk.getSdt());
		txtEmail.setText(tk.getEmail());
		if (tk.getQuyen() == 1)
			cbbPhanQuyen.setSelectedIndex(1);
		else
			cbbPhanQuyen.setSelectedIndex(0);
		if (tk.getTruyCap() == 1)
			getRad(radCo);
		else {
			getRad(radKhong);
		}

	}

	public void Them() {
		if (kiemTraNhap()) {
			TaiKhoan tk = getTaiKhoan();
			main.taiKhoan_pn.ThemTaiKhoan(tk);
			dispose();
		}
	}

	public void CapNhat() {
		if (kiemTraNhap()) {
			TaiKhoan tk = getTaiKhoan();
			main.taiKhoan_pn.CapNhatTaiKhoan(tk);
			dispose();
		}
	}

	public boolean kiemTraNhap() {
		String tenTK = txtTenTK.getText();
		String hoTen = txtHoTen.getText();
		String email = txtEmail.getText();
		String sdt = txtSDT.getText();
		String matKhau = txtMatKhau.getText();

		if (tenTK.equals("") || hoTen.equals("") || matKhau.equals("") || sdt.equals("") || email.equals("")) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
			return false;
		}
		if (sdt.length() != 10) {
			txtSDT.requestFocus();
			JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại hợp lệ với 10 số");
			return false;
		}
		return true;
	}

	public TaiKhoan getTaiKhoan() {
		String tenTK = txtTenTK.getText();
		String matKhau = txtMatKhau.getText();
		String hoTen = txtHoTen.getText();
		String email = txtEmail.getText();
		String sdt = txtSDT.getText();
		String Squyen = (String) cbbPhanQuyen.getSelectedItem();
		int quyen;
		int truyCap;
		if (Squyen.equals("Nhân viên"))
			quyen = 2;
		else
			quyen = 1;
		if (radCo.isSelected())
			truyCap = 1;
		else
			truyCap = 2;
		TaiKhoan tk = new TaiKhoan(tenTK, matKhau, hoTen, email, sdt, quyen, truyCap);
		return tk;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TaiKhoan_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TaiKhoan_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TaiKhoan_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TaiKhoan_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				TaiKhoan_Dialog dialog = new TaiKhoan_Dialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
//                dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLuu;
	private javax.swing.JButton btnXoaTrang;
	private javax.swing.JComboBox<String> cbbPhanQuyen;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JRadioButton radCo;
	private javax.swing.JRadioButton radKhong;
	private javax.swing.JTextField txtEmail;
	private javax.swing.JTextField txtHoTen;
	private javax.swing.JTextField txtMatKhau;
	private javax.swing.JTextField txtSDT;
	private javax.swing.JTextField txtTenTK;

	private QuanLyTaiKhoan qltk;
	private Main_Gui main;
	public static int quyen;
	// End of variables declaration//GEN-END:variables
}
