/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_main;

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DatabaseMetaData;
import java.awt.print.*;
import java.text.*;

import javax.swing.JPanel;

import entities.TaiKhoan;
import gui_baocao.BaoCao_Dia_Gui;
import gui_danhMuc.Dia_Gui;
import gui_danhMuc.KhachHang_Gui;
import gui_danhMuc.TenDia_Gui;
import gui_giaodich.DatHang_Gui;
import gui_giaodich.PhieuThue_Gui;
import gui_giaodich.PhieuTra_Gui;
import gui_giaodich.TraCuu_Dia_Gui;
import gui_heThong.QuiDinh_Dialog;
import gui_heThong.TaiKhoan_Gui;
import gui_heThong.TroGiup_Gui;
import gui_taiKhoan.DangNhap_Dialog;
import gui_taiKhoan.DoiMatKhau_Dialog;

/**
 *
 * @author nmrhu
 */
public class Main_Gui extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */

	public Main_Gui() {
		initComponents();
		khoiTaoPanel();
		dangXuat();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		txtPrint = new javax.swing.JTextField();

		jMenu1 = new javax.swing.JMenu();
		jPanel1 = new javax.swing.JPanel();
		jMenuBar1 = new javax.swing.JMenuBar();
		mnTaiKhoan = new javax.swing.JMenu();
		DangNhap = new javax.swing.JMenuItem();
		DoiMatKhau = new javax.swing.JMenuItem();
		DangXuat = new javax.swing.JMenuItem();
		Thoat = new javax.swing.JMenuItem();
		mnHeThong = new javax.swing.JMenu();
		QLNguoiDung = new javax.swing.JMenuItem();
		ThietLapGia = new javax.swing.JMenuItem();
		HoTro = new javax.swing.JMenuItem();
		mnDanhMuc = new javax.swing.JMenu();
		DM_KhachHang = new javax.swing.JMenuItem();
		DM_TenDia = new javax.swing.JMenuItem();
		DM_Dia = new javax.swing.JMenuItem();
		mnBaoCao = new javax.swing.JMenu();
		BC_KhachHang = new javax.swing.JMenuItem();
		BD_Dia = new javax.swing.JMenuItem();
		BD_DoanhThu = new javax.swing.JMenuItem();
		mnGiaoDich = new javax.swing.JMenu();
		TraCuu = new javax.swing.JMenuItem();
		PhieuThue = new javax.swing.JMenuItem();
		PhieuTra = new javax.swing.JMenuItem();
		DatHang = new javax.swing.JMenuItem();

		jMenu1.setText("jMenu1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Hệ thống quản lý cho thuê băng đĩa");
		setBackground(new java.awt.Color(255, 255, 255));
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setPreferredSize(new java.awt.Dimension(1320, 780));
		setResizable(false);

		jPanel1.setPreferredSize(new java.awt.Dimension(1300, 650));
		jPanel1.setLayout(new java.awt.BorderLayout());
		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
		jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 24));
		setJMenuBar(jMenuBar1);

		mnTaiKhoan.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-male-user-48.png")); // NOI18N
		mnTaiKhoan.setText("Tài khoản");
		mnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 24));
		mnTaiKhoan.setFocusable(false);

		DangNhap.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-login-48.png")); // NOI18N
		DangNhap.setText("Đăng nhập");
		DangNhap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DangNhapActionPerformed(evt);
			}
		});
		mnTaiKhoan.add(DangNhap);

		DoiMatKhau.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-locked-with-key-48.png")); // NOI18N
		DoiMatKhau.setText("Đổi mật khẩu");
		DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DoiMatKhauActionPerformed(evt);
			}
		});
		mnTaiKhoan.add(DoiMatKhau);

		DangXuat.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-export-48.png")); // NOI18N
		DangXuat.setText("Đăng xuất");
		DangXuat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dangXuat();
			}
		});
		mnTaiKhoan.add(DangXuat);

		Thoat.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-shutdown-48.png")); // NOI18N
		Thoat.setText("Thoát");
		Thoat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ThoatActionPerformed(evt);
			}
		});
		mnTaiKhoan.add(Thoat);

		jMenuBar1.add(mnTaiKhoan);

		mnHeThong.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-gear-48.png")); // NOI18N
		mnHeThong.setText("Hệ thống");
		mnHeThong.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

		QLNguoiDung.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-management-48.png")); // NOI18N
		QLNguoiDung.setText("Quản lý người dùng");
		QLNguoiDung.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				thayDoiManHinh(taiKhoan_pn);
			}
		});
		mnHeThong.add(QLNguoiDung);

		ThietLapGia.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-clipboard-48.png")); // NOI18N
		ThietLapGia.setText("Thiết lập giá");
		ThietLapGia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ThietLapGiaActionPerformed(evt);
			}
		});
		mnHeThong.add(ThietLapGia);

		HoTro.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-info-48.png")); // NOI18N
		HoTro.setText("Hỗ trợ");
		HoTro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				thayDoiManHinh(troGiup_pn);
			}
		});
		mnHeThong.add(HoTro);

		jMenuBar1.add(mnHeThong);

		mnDanhMuc.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-list-48.png")); // NOI18N
		mnDanhMuc.setText("Danh mục");
		mnDanhMuc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

		DM_KhachHang.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-user-group-48.png")); // NOI18N
		DM_KhachHang.setText("Khách hàng");

		DM_KhachHang.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				thayDoiManHinh(khachHang_pn);
				khachHang_pn.phanQuyen(tk);
			}
		});
		mnDanhMuc.add(DM_KhachHang);

		DM_TenDia.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-dvd-logo-48.png")); // NOI18N
		DM_TenDia.setText("Tên đĩa");
		DM_TenDia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				thayDoiManHinh(tenDia_pn);
			}
		});
		mnDanhMuc.add(DM_TenDia);

		DM_Dia.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-dvd-48.png")); // NOI18N
		DM_Dia.setText("Đĩa");
		DM_Dia.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				thayDoiManHinh(dia_pn);
			}
		});
		mnDanhMuc.add(DM_Dia);

		jMenuBar1.add(mnDanhMuc);

		mnBaoCao.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-combo-chart-48.png")); // NOI18N
		mnBaoCao.setText("Báo cáo");
		mnBaoCao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

		BC_KhachHang.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-user-group-48.png")); // NOI18N
		BC_KhachHang.setText("Khách hàng");
		BC_KhachHang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				
			}
		});
		mnBaoCao.add(BC_KhachHang);

		BD_Dia.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-dvd-logo-48.png")); // NOI18N
		BD_Dia.setText("Đĩa");
		mnBaoCao.add(BD_Dia);
		BD_Dia.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				thayDoiManHinh(bcDia_pn);
			}
		});

		BD_DoanhThu.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-stack-of-coins-48.png")); // NOI18N
		BD_DoanhThu.setText("Doanh thu");
		mnBaoCao.add(BD_DoanhThu);

		jMenuBar1.add(mnBaoCao);

		mnGiaoDich.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-data-transfer-48.png")); // NOI18N
		mnGiaoDich.setText("Giao dịch");
		mnGiaoDich.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

		TraCuu.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-search-48.png")); // NOI18N
		TraCuu.setText("Tra cứu");
		TraCuu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				thayDoiManHinh(traCuu_pn);
			}
		});
		mnGiaoDich.add(TraCuu);

		PhieuThue.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-add-property-48.png")); // NOI18N
		PhieuThue.setText("Phiếu thuê");
		PhieuThue.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				phieuThue_pn.setData(tk);
				thayDoiManHinh(phieuThue_pn);
				phieuThue_pn.dsPhieu(tk);
			}
		});
		mnGiaoDich.add(PhieuThue);

		PhieuTra.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-edit-property-48.png")); // NOI18N
		PhieuTra.setText("Ghi nhận trả");
		PhieuTra.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				phieuTra_pn.setData(tk);
				thayDoiManHinh(phieuTra_pn);
				phieuTra_pn.dsPhieuTra(tk);
			}
		});
		mnGiaoDich.add(PhieuTra);

		DatHang.setIcon(new javax.swing.ImageIcon(
				"D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\QuanLy\\img\\icons8-search-property-48.png")); // NOI18N
		DatHang.setText("Đặt hàng");
		DatHang.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				datHang_pn.setData(tk);
				thayDoiManHinh(datHang_pn);

			}
		});
		mnGiaoDich.add(DatHang);

		jMenuBar1.add(mnGiaoDich);

		setJMenuBar(jMenuBar1);

		pack();
	}

	private void ThietLapGiaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ThietLapGiaActionPerformed
		thietLapGia_pn = new QuiDinh_Dialog(this, rootPaneCheckingEnabled);
		thietLapGia_pn.setTitle("Cập nhật giá cho thuê");
		thietLapGia_pn.setLocationRelativeTo(this);
		thietLapGia_pn.setVisible(rootPaneCheckingEnabled);
	}

	private void DangNhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DangNhapActionPerformed
		dangNhap_pn = new DangNhap_Dialog(this, rootPaneCheckingEnabled);
		dangNhap_pn.setTitle("Đăng nhập");
		dangNhap_pn.setLocationRelativeTo(this);
		dangNhap_pn.setVisible(rootPaneCheckingEnabled);
	}

	private void DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DoiMatKhauActionPerformed
		doiMatKhau_pn = new DoiMatKhau_Dialog(this, rootPaneCheckingEnabled);
		doiMatKhau_pn.setTitle("Đổi mật khẩu");
		doiMatKhau_pn.setLocationRelativeTo(this);
		doiMatKhau_pn.setData(tk);
		doiMatKhau_pn.setVisible(rootPaneCheckingEnabled);
	}

	private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ThoatActionPerformed
		System.exit(0);
	}

	public void khoiTaoPanel() {
		khachHang_pn = new KhachHang_Gui();
		dia_pn = new Dia_Gui();
		tenDia_pn = new TenDia_Gui();
		taiKhoan_pn = new TaiKhoan_Gui();
		troGiup_pn = new TroGiup_Gui();
		phieuThue_pn = new PhieuThue_Gui();
		phieuTra_pn = new PhieuTra_Gui();
		datHang_pn = new DatHang_Gui();
		traCuu_pn = new TraCuu_Dia_Gui();
		bcDia_pn = new BaoCao_Dia_Gui();

		thayDoiManHinh(troGiup_pn);
	}

	public void thayDoiManHinh(JPanel panel) {
		bcDia_pn.setVisible(false);
		khachHang_pn.setVisible(false);
		dia_pn.setVisible(false);
		tenDia_pn.setVisible(false);
		taiKhoan_pn.setVisible(false);
		troGiup_pn.setVisible(false);
		phieuThue_pn.setVisible(false);
		phieuTra_pn.setVisible(false);
		datHang_pn.setVisible(false);
		traCuu_pn.setVisible(false);

		jPanel1.add(panel);
		panel.setVisible(true);
	}

	public void dangXuat() {
		DangNhap.setEnabled(true);
		mnBaoCao.setEnabled(false);
		mnDanhMuc.setEnabled(false);
		mnGiaoDich.setEnabled(false);

		QLNguoiDung.setEnabled(false);
		ThietLapGia.setEnabled(false);

		DM_Dia.setEnabled(true);
		DM_TenDia.setEnabled(true);

		DoiMatKhau.setEnabled(false);
		DangXuat.setEnabled(false);

		thayDoiManHinh(troGiup_pn);
	}

	public static void setNhanVien(TaiKhoan tk_sql) {
		tk = tk_sql;

		DangNhap.setEnabled(false);

		mnDanhMuc.setEnabled(true);
		DM_Dia.setEnabled(false);
		DM_TenDia.setEnabled(false);
		mnGiaoDich.setEnabled(true);

		DoiMatKhau.setEnabled(true);
		DangXuat.setEnabled(true);
	}

	public static void setQuanLy(TaiKhoan tk_sql) {
		tk = tk_sql;

		DangNhap.setEnabled(false);

		mnBaoCao.setEnabled(true);
		mnDanhMuc.setEnabled(true);
		mnGiaoDich.setEnabled(true);

		QLNguoiDung.setEnabled(true);
		ThietLapGia.setEnabled(true);

		DoiMatKhau.setEnabled(true);
		DangXuat.setEnabled(true);
	}

	public void setData(TaiKhoan tk_sql) {
		tk = tk_sql;
		System.out.println(tk.getTenTK());
	}

	public void print() throws PrinterException {
			try {
				String bill = "";
				bill = "=========Bill===========";
				txtPrint.setText(bill);
				txtPrint.print();
			} catch (Exception r) {
				r.printStackTrace();
			}
		}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main_Gui().setVisible(true);
			}
		});
	}

	private TroGiup_Gui troGiup_pn;
	private QuiDinh_Dialog thietLapGia_pn;
	private DoiMatKhau_Dialog doiMatKhau_pn;

	public static BaoCao_Dia_Gui bcDia_pn;
	public static DangNhap_Dialog dangNhap_pn;
	public static TaiKhoan_Gui taiKhoan_pn;
	public static KhachHang_Gui khachHang_pn;
	public static TenDia_Gui tenDia_pn;
	public static Dia_Gui dia_pn;
	public static TraCuu_Dia_Gui traCuu_pn;
	public static PhieuThue_Gui phieuThue_pn;
	public static PhieuTra_Gui phieuTra_pn;
	public static DatHang_Gui datHang_pn;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem BC_KhachHang;
	private javax.swing.JMenuItem BD_Dia;
	private javax.swing.JMenuItem BD_DoanhThu;
	private static javax.swing.JMenuItem DM_Dia;
	private javax.swing.JMenuItem DM_KhachHang;
	private static javax.swing.JMenuItem DM_TenDia;
	private static javax.swing.JMenuItem DangNhap;
	private static javax.swing.JMenuItem DangXuat;
	private javax.swing.JMenuItem DatHang;
	private static javax.swing.JMenuItem DoiMatKhau;
	private javax.swing.JMenuItem HoTro;
	private javax.swing.JMenuItem PhieuThue;
	private javax.swing.JMenuItem PhieuTra;
	private static javax.swing.JMenuItem QLNguoiDung;
	private static javax.swing.JMenuItem ThietLapGia;
	private javax.swing.JMenuItem Thoat;
	private javax.swing.JMenuItem TraCuu;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private static javax.swing.JMenu mnBaoCao;
	private static javax.swing.JMenu mnDanhMuc;
	private static javax.swing.JMenu mnGiaoDich;
	private static javax.swing.JMenu mnHeThong;
	private javax.swing.JMenu mnTaiKhoan;

	public static TaiKhoan tk;
	
	private javax.swing.JTextField txtPrint;
	// End of variables declaration//GEN-END:variables
}
