package gui_taiKhoan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import database.Database;
import entities.TaiKhoan;
import gui_main.Main_Gui;
import service.QuanLyTaiKhoan;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nmrhu
 */
public class DangNhap_Dialog extends javax.swing.JDialog {

	/**
	 * Creates new form NewJDialog
	 */
	public DangNhap_Dialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		Database.getInstance().connect();
		qltk = new QuanLyTaiKhoan();

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtTenTaiKhoan = new javax.swing.JTextField();
		txtMatKhau = new javax.swing.JTextField();
		btnDangNhap = new javax.swing.JButton();
		btnDong = new javax.swing.JButton();
		
		btnDong.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jLabel1.setText("Tên đăng nhập:");

		jLabel2.setText("Mật khẩu:");

		btnDangNhap.setBackground(new java.awt.Color(0, 153, 255));
		btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
		btnDangNhap.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\login_30px.png")); // NOI18N
		btnDangNhap.setText("Đăng nhập");
		btnDangNhap.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				if (kiemTraNhap()) {
					if (kiemTraTaiKhoan()) {
						if (kiemTraMatKhau()) {
							if (kiemTraTruyCap()) {
								if (tk_sql.getQuyen() == 1) {
									main.setNhanVien(tk_sql);
									dispose();
								} else {
									main.setQuanLy(tk_sql);
									dispose();
								}
							}
						}
					}
				}
			}
		});

		btnDong.setBackground(new java.awt.Color(255, 0, 0));
		btnDong.setForeground(new java.awt.Color(255, 255, 255));
		btnDong.setIcon(
				new javax.swing.ImageIcon("D:\\HK1_Nam_4\\XayDungPhanMem\\Netbeans\\DemoGui\\img\\delete_30px.png")); // NOI18N
		btnDong.setText("Đóng");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 333,
												Short.MAX_VALUE)
										.addComponent(txtMatKhau))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup()
										.addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 154,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29,
												Short.MAX_VALUE)
										.addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(18, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel1)
						.addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(btnDangNhap).addComponent(btnDong))
				.addContainerGap(35, Short.MAX_VALUE)));

		pack();
	}

	public boolean kiemTraTruyCap() {
		if (tk_sql.getTruyCap() == 0) {
			JOptionPane.showMessageDialog(null, "Tài khoản không được phép truy cập");
			return false;
		}
		return true;
	}

	public boolean kiemTraMatKhau() {
		if (!tk_sql.getMatKhau().equalsIgnoreCase(tk.getMatKhau())) {
			JOptionPane.showMessageDialog(null, "Mật khẩu không hợp lệ");
			txtMatKhau.requestFocus();
			return false;
		}
		return true;
	}

	public boolean kiemTraTaiKhoan() {
		tk_sql = qltk.chiTietTaiKhoan(tk.getTenTK());
		if (tk_sql == null) {
			JOptionPane.showMessageDialog(null, "Tài khoản không hợp lệ");
			txtTenTaiKhoan.requestFocus();
			return false;
		}
		return true;
	}

	public boolean kiemTraNhap() {
		tk = getTaiKhoan();
		if (tk.getTenTK().equalsIgnoreCase("") || tk.getMatKhau().equalsIgnoreCase("")) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ");
			return false;
		}
		return true;
	}

	public TaiKhoan getTaiKhoan() {
		String tenTK = txtTenTaiKhoan.getText();
		String matKhau = txtMatKhau.getText();
		TaiKhoan tk = new TaiKhoan(tenTK, matKhau);
		return tk;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DangNhap_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DangNhap_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DangNhap_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DangNhap_Dialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DangNhap_Dialog dialog = new DangNhap_Dialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDangNhap;
	private javax.swing.JButton btnDong;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField txtMatKhau;
	private javax.swing.JTextField txtTenTaiKhoan;

	private QuanLyTaiKhoan qltk;

	private TaiKhoan tk;
	private TaiKhoan tk_sql;

	public static Main_Gui main;
	// End of variables declaration//GEN-END:variables
}
